version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      postgres_db:
        condition: service_healthy
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ipl
      POSTGRES_USER: postgres
      POSTGRES_DB: exoplanets
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/createdb.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data: