openapi: 3.0.3
info:
  title: Catflix review service
  description: Microservice handling database of reviews in project Catflix
  version: 1.0.0
servers:
  - url: http://localhost:9003
    description: Development server
paths:

  /reviews/{pseudo}/{hash}:
    parameters:
      - name: pseudo
        in: path
        required: true
        description: Pseudo of the user
        schema:
          type: string
      - name: hash
        in: path
        required: true
        description: Hash of the video
        schema:
          type: string

    post:
      summary: Create new review
      requestBody:
        description: Review to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/review'
      responses:
        400:
          description: Pseudo and/or hash does not match, or review invalid
        409:
          description: Review already exists
        201:
          description: Review created

    get:
      summary: Read review
      responses:
        404:
          description: Review not found
        200:
          description: Review found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/review'

    put:
      summary: Update review
      requestBody:
        description: New values of the review
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/review'
      responses:
        400:
          description: Pseudo and/or hash does not match, or review invalid
        404:
          description: Review not found
        200:
          description: Review updated

    delete:
      summary: Delete review
      responses:
        404:
          description: Review not found
        200:
          description: Review deleted

  /reviews/user/{pseudo}:
    parameters:
      - name: pseudo
        in: path
        required: true
        description: Pseudo of the user
        schema:
          type: string

    get:
      summary: Find reviews from a user
      responses:
        200:
          description:  Reviews from the user
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/review'

    delete:
      summary: Delete reviews from a user
      responses:
        200:
          description: Reviews deleted

  /reviews/video/{hash}:
    parameters:
      - name: hash
        in: path
        required: true
        description: Hash of the video
        schema:
          type: string

    get:
      summary: Find reviews of a video
      responses:
        200:
          description: Reviews of the video
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/review'

    delete:
      summary: Delete reviews of a video
      responses:
        200:
          description: Reviews deleted

  /reviews/best:
    get:
      summary: Find the best 3 videos
      responses:
        200:
          description: Highest rated videos by the users
          content:
            'application/json':
              schema:
                type: array
                maxItems: 3
                items:
                  $ref: '#/components/schemas/video'


components:
  schemas:
    review:
      type: object
      properties:
        pseudo:
          type: string
        hash:
          type: string
        rating:
          type: number
        comment:
          type: string
      example:
        pseudo: Cat4Life
        hash: dQw4w9WgXcQ
        rating: 10
        comment: Best video!
    video:
      type: object
      properties:
        hash:
          type: string
        name:
          type: string
        author:
          type: string
        creationYear:
          type: integer
        duration:
          type: integer
          description: in seconds
        url:
          type: string
      example:
        hash: dQw4w9WgXcQ
        name: Cutest kitty ever
        author: Cat4Life
        creationYear: 2009
        duration: 212
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
