version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  nodejs_app:
    build: ./exoplanets
    ports:
      - "7000:3000"
    depends_on:
      - mongo

  mongo_express:
    image: mongo-express
    ports:
      - "8000:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
