### Ajouter un produit à la wishlist de l'utilisateur
PUT {{baseUrl}}/wishlists/nitroc/1

### Supprimer un produit de la wishlist de l'utilisateur
DELETE {{baseUrl}}/wishlists/nitroc/1

### Récupérer les produits de la wishlist de l'utilisateur
GET {{baseUrl}}/wishlists/user/nitroc

### Supprimer la wishlist de l'utilisateur
DELETE {{baseUrl}}/wishlists/user/nitroc

### Supprimer le produit de la wishlist de tous les utilisateurs
DELETE {{baseUrl}}/wishlists/products/1