### Get the latest price for a ticker
GET http://localhost:9006/price/AAPL

### Update the price for a ticker
PATCH http://localhost:9006/price/AAPL
Content-Type: application/json

150.0


### Get the latest price for a ticker that does not exist
GET http://localhost:9006/price/TEST

### Update the price for a ticker that does not exist
PATCH http://localhost:9006/price/TEST1
Content-Type: application/json

350.2

### Update the price for a ticker with invalid price
PATCH http://localhost:9006/price/AAPL
Content-Type: application/json

-50.0